// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEVEyeAjez5iu-kZ2GZMpJSYAQioT_llE',
    appId: '1:148956304557:web:27b6f9ac0ee13095b6a224',
    messagingSenderId: '148956304557',
    projectId: 'exe-platform',
    authDomain: 'exe-platform.firebaseapp.com',
    storageBucket: 'exe-platform.firebasestorage.app',
    measurementId: 'G-DZV31QW5HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcfKg1aD1CJvzaI2rx1y96tA3tRVe6rU',
    appId: '1:148956304557:android:d282b64e71d49071b6a224',
    messagingSenderId: '148956304557',
    projectId: 'exe-platform',
    storageBucket: 'exe-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jETK2HYnN_fIPRynwihRy09mfqI9DME',
    appId: '1:148956304557:ios:0c85ec9fbd2f2e64b6a224',
    messagingSenderId: '148956304557',
    projectId: 'exe-platform',
    storageBucket: 'exe-platform.firebasestorage.app',
    iosClientId: '148956304557-po5tes337e6r5io4497omktsf4t5em68.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingGroupFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jETK2HYnN_fIPRynwihRy09mfqI9DME',
    appId: '1:148956304557:ios:0c85ec9fbd2f2e64b6a224',
    messagingSenderId: '148956304557',
    projectId: 'exe-platform',
    storageBucket: 'exe-platform.firebasestorage.app',
    iosClientId: '148956304557-po5tes337e6r5io4497omktsf4t5em68.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingGroupFlutter',
  );
}
